version: '3'

services:
  redis:
    image: redis:7-alpine
    environment:
      TZ: Asia/Bangkok
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    # command: --appendonly yes --timeout 0

volumes:
  redis-data:
